### PR TITLE
Remove spacing

### PR DESCRIPTION
**Pull request by gargi**
Fix for issue #3

### CODE REVIEW

**Comment by gargi** [comment]
Fix for #3, #2, #5

**Comment by smalleni** [comment]
oops, just saw your issues but not your pull request..i fixed most of these when i saw the issues and now there are merge conflicts..can you create a different branch and commit changes which are still not reflected so that it will be easier to avoid merge conflicts.

**Comment by gargi** [comment]
Hi, actually according to the guidelines I am supposed to fix 3 issues. So can you please go back to the previous commit so that I can merge this pull request?

**Comment by smalleni** [comment]
How do you go back on a commit?...just undo the changes and commit again or
is there a better way you know of?

On Mon, Oct 19, 2015 at 5:53 PM, Gargi Rajadhyaksha <
notifications@github.com> wrote:

> Hi, actually according to the guidelines I am supposed to fix 3 issues. So
> can you please go back to the previous commit so that I can merge this pull
> request?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-ImpactMiner/pull/7#issuecomment-149359014
> .

## 

Sai Sindhur Malleni
Performance Engineering Intern
Red Hat Inc.
100 East Davie Street
Raleigh, NC, USA
Work: (919) 890-8633 | Cell:(919) 985-1055

**Comment by gargi** [comment]
There is a simple way of doing it. Do you have Github desktop? You can just go back to the commit before the pull request and click on settings-> "Revert this commit". Thanks.

**Comment by smalleni** [comment]
Don't have a windows machine now..but will figure out a way..sorry for the
trouble

On Mon, Oct 19, 2015 at 8:31 PM, Gargi Rajadhyaksha <
notifications@github.com> wrote:

> There is a simple way of doing it. Do you have Github desktop? You can
> just go back to the commit before the pull request and click on settings->
> "Revert this commit". Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-ImpactMiner/pull/7#issuecomment-149385068
> .

## 

Sai Sindhur Malleni
Performance Engineering Intern
Red Hat Inc.
100 East Davie Street
Raleigh, NC, USA
Work: (919) 890-8633 | Cell:(919) 985-1055

**Comment by gargi** [comment]
screen shot 2015-10-19 at 8 33 43 pm

**Comment by gargi** [comment]
It works on Mac too. Just do this much.

**Comment by smalleni** [comment]
I run a Fedora 22 :D I will surely look into this. Have a midterm tomorrow.
Once again. sorry about the oversight

On Mon, Oct 19, 2015 at 8:34 PM, Gargi Rajadhyaksha <
notifications@github.com> wrote:

> It works on Mac too. Just do this much.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SoftwareEngineeringToolDemos/ICSE-2014-ImpactMiner/pull/7#issuecomment-149385499
> .

## 

Sai Sindhur Malleni
Performance Engineering Intern
Red Hat Inc.
100 East Davie Street
Raleigh, NC, USA
Work: (919) 890-8633 | Cell:(919) 985-1055

**Pull request closed without merging**
